Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 515, in <module>
    class MultiLayerDiscriminator(nn.Module):
NameError: name 'nn' is not defined
E1018 00:23:33.626000 22751202841728 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 2008070) of binary: /hpctmp/e0833524/virtualenvs/cogvideo/bin/python
Traceback (most recent call last):
  File "/hpctmp/e0833524/virtualenvs/cogvideo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
KD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2008071)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2008072)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2008073)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2008074)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 2008075)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 2008076)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 2008077)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-18_00:23:33
  host      : hopper-04.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2008070)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
