/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank0]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank0]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank5]: Traceback (most recent call last):
[rank5]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank5]:     main(args)
[rank5]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank5]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank5]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank2]:     main(args)
[rank2]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank2]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank2]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank3]:     main(args)
[rank3]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank3]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank3]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank1]:     main(args)
[rank1]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank1]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank1]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank7]:     main(args)
[rank7]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank7]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank7]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank4]: Traceback (most recent call last):
[rank4]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank4]:     main(args)
[rank4]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank4]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank4]: ImportError: Make sure to install wandb if you want to use it for logging during training.
[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 1209, in <module>
[rank6]:     main(args)
[rank6]:   File "/home/svu/e0833524/CogVideo/finetune/KD.py", line 713, in main
[rank6]:     raise ImportError("Make sure to install wandb if you want to use it for logging during training.")
[rank6]: ImportError: Make sure to install wandb if you want to use it for logging during training.
E1016 18:58:51.966000 22597049676928 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 1388787) of binary: /hpctmp/e0833524/virtualenvs/cogvideo/bin/python
Traceback (most recent call last):
  File "/hpctmp/e0833524/virtualenvs/cogvideo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/hpctmp/e0833524/virtualenvs/cogvideo/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
KD.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1388788)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1388789)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1388790)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 1388791)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 1388792)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 1388793)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 1388794)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-16_18:58:51
  host      : hopper-04.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1388787)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
